---
version: '3.7'

services:
  borghost:
    image: sintelli/borghost:latest
    container_name: borghost
    restart: always
    environment:
      REPO: ${REPO}
      SSH_AUTHORIZED_KEY: ${SSH_AUTHORIZED_KEY}
      SSH_PORT: ${SSH_PORT}
      REMOTE_USER: ${REMOTE_USER}
      REMOTE_HOST: ${REMOTE_HOST}
      REMOTE_BIND_IP: ${REMOTE_BIND_IP}
      REMOTE_BIND_PORT: ${REMOTE_BIND_PORT}
    volumes:
      - ./data:/data
      - ./backups:${REPO}
